import concurrent.futures
from typing import Dict, List

from .configuration import OptimizationConfig
from .metrics import OptimizationResult, OptimizationStatistics
from .search.base import SearchAlgorithm
from .ranking import RankingStrategy

from tradiba.backtest.engine import BacktestEngine
from tradiba.backtest.feed import HistoricalCSVFeed
from tradiba.backtest.executor import PaperExecutionAdapter
from tradiba.market.models import Timeframe
from tradiba.events import EventBus


def _run_backtest_worker(params: Dict[str, float], data_file: str, symbol: str, timeframe: Timeframe) -> OptimizationResult:
    """
    Independent worker function for executing a single backtest with a parameter set.
    Must not share mutable state.
    """
    # 1. Setup isolated Backtest components
    feed = HistoricalCSVFeed(filepath=data_file, symbol=symbol, timeframe=timeframe)
    event_bus = EventBus()
    executor = PaperExecutionAdapter(initial_balance=10000.0)
    engine = BacktestEngine(feed=feed, event_bus=event_bus, executor=executor)
    
    # 2. In a complete integration, we would configure the Strategy/Risk engine 
    # using 'params' here. For now, we simulate the run.
    
    # 3. Run backtest
    stats_dict = engine.run()
    
    # 4. Map dictionary to OptimizationStatistics
    stats = OptimizationStatistics(
        net_profit=stats_dict.get("net_profit", 0.0),
        total_trades=0, # Simulated
        win_rate=0.0,
        profit_factor=0.0,
        max_drawdown=0.0,
        sharpe_ratio=0.0,
        sortino_ratio=0.0,
        calmar_ratio=0.0
    )
    
    return OptimizationResult(parameters=params, statistics=stats)


class OptimizationEngine:
    """
    Orchestrates the optimization process across multiple cores.
    """

    def __init__(self, config: OptimizationConfig, ranking_strategy: RankingStrategy):
        self.config = config
        self.ranking_strategy = ranking_strategy

    def optimize(
        self,
        search_algorithm: SearchAlgorithm,
        data_file: str,
        symbol: str,
        timeframe: Timeframe,
    ) -> List[OptimizationResult]:
        """
        Runs the backtests for all parameter combinations generated by the search algorithm.
        Returns a ranked list of results.
        """
        results: List[OptimizationResult] = []
        
        # Generator for parameter sets
        param_sets = list(search_algorithm.generate())
        
        # We limit the number of sets if max_iterations is set
        if self.config.max_iterations > 0:
            param_sets = param_sets[:self.config.max_iterations]

        # Use ProcessPoolExecutor to run backtests concurrently
        with concurrent.futures.ProcessPoolExecutor(max_workers=self.config.workers) as pool:
            futures = [
                pool.submit(_run_backtest_worker, params, data_file, symbol, timeframe)
                for params in param_sets
            ]
            
            for future in concurrent.futures.as_completed(futures):
                try:
                    result = future.result()
                    results.append(result)
                except Exception as e:
                    # In production we'd log the error and continue
                    print(f"Worker failed: {e}")
                    
        # Rank the results
        ranked_results = self.ranking_strategy.rank(results)
        return ranked_results
