"""
Strategy domain models.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Direction(Enum):
    LONG = "LONG"
    SHORT = "SHORT"


@dataclass(frozen=True, slots=True)
class Signal:
    """
    A trading signal generated by a strategy.
    This is not an order — it must be validated by risk management first.
    """

    symbol: str
    direction: Direction
    entry: float
    stop_loss: float
    take_profit: float
    confidence: float
    strategy_id: str
