from typing import Dict, Any

from tradiba.hermes.live.approvals.workflow import ExecutionApprovalFramework

class AdaptiveGovernance:
    """
    Ensures any adaptive plan generated by the World Model passes through production governance boundaries.
    """
    def __init__(self, approval_framework: ExecutionApprovalFramework):
        self.approval_framework = approval_framework
        
    def process_adaptive_plan(self, plan: Dict[str, Any], current_state: Dict[str, Any]) -> str:
        """
        Validates the plan and passes to Live Governance.
        """
        # Ensure plan was properly evaluated
        if "risk_score" not in plan:
            return "REJECTED_NO_RISK_SCORE"
            
        if plan["risk_score"] > 0.8:
            return "REJECTED_EXCESSIVE_RISK"
            
        decision = plan.get("decision", {"action": plan.get("action", "unknown")})
        # Passes to Live Workflow
        return self.approval_framework.process_decision(decision, current_state, risk_approved=True)
