from abc import ABC, abstractmethod
from typing import List

from tradiba.events import Event
from tradiba.mt5.models import Candle
from tradiba.market_structure.state import MarketStructureState

class Detector(ABC):
    """
    Base interface for all market structure detectors.
    """
    @abstractmethod
    def update(self, candle: Candle, state: TimeframeState, current_events: List[Event]) -> List[Event]:
        """
        Process the new candle, update the state, and return any generated events.
        `current_events` contains events generated by previously run detectors in the same cycle.
        """
        pass
