from tradiba.market_structure.state import MarketStructureState
from abc import ABC, abstractmethod
from typing import List

from tradiba.events import DomainEvent
from tradiba.mt5.models import Candle

class Detector(ABC):
    """
    Base interface for all market structure detectors.
    """
    @abstractmethod
    def update(self, candle: Candle, state: MarketStructureState, current_events: List[DomainEvent]) -> List[DomainEvent]:
        """
        Process the new candle, update the state, and return any generated events.
        `current_events` contains events generated by previously run detectors in the same cycle.
        """
        pass
