"""Initial persistence and event store

Revision ID: e799661a3ddd
Revises: 
Create Date: 2026-07-25 13:24:44.176356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e799661a3ddd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('tick_volume', sa.Integer(), nullable=False),
    sa.Column('real_volume', sa.Integer(), nullable=False),
    sa.Column('spread', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_aggregate_id'), 'events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_sequence'), 'events', ['sequence'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('trade_plan_id', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_price', sa.Numeric(), nullable=False),
    sa.Column('executed_price', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_execution_id'), 'executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_executions_trade_plan_id'), 'executions', ['trade_plan_id'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_events_event_type'), 'market_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_market_events_timestamp'), 'market_events', ['timestamp'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('version')
    )
    op.create_table('ticks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Numeric(), nullable=False),
    sa.Column('ask', sa.Numeric(), nullable=False),
    sa.Column('last', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticks_symbol'), 'ticks', ['symbol'], unique=False)
    op.create_index(op.f('ix_ticks_timestamp'), 'ticks', ['timestamp'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('equity', sa.Numeric(), nullable=False),
    sa.Column('margin', sa.Numeric(), nullable=False),
    sa.Column('free_margin', sa.Numeric(), nullable=False),
    sa.Column('margin_level', sa.Numeric(), nullable=False),
    sa.Column('floating_profit', sa.Numeric(), nullable=False),
    sa.Column('realized_profit', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_version'], ['snapshots.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_snapshot_version'), 'accounts', ['snapshot_version'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broker_state', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_version'], ['snapshots.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_snapshot_version'), 'orders', ['snapshot_version'], unique=False)
    op.create_index(op.f('ix_orders_ticket'), 'orders', ['ticket'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('current_price', sa.Numeric(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(), nullable=False),
    sa.Column('take_profit', sa.Numeric(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profit', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_version'], ['snapshots.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_snapshot_version'), 'positions', ['snapshot_version'], unique=False)
    op.create_index(op.f('ix_positions_ticket'), 'positions', ['ticket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_ticket'), table_name='positions')
    op.drop_index(op.f('ix_positions_snapshot_version'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_ticket'), table_name='orders')
    op.drop_index(op.f('ix_orders_snapshot_version'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_accounts_snapshot_version'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_ticks_timestamp'), table_name='ticks')
    op.drop_index(op.f('ix_ticks_symbol'), table_name='ticks')
    op.drop_table('ticks')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_market_events_timestamp'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_event_type'), table_name='market_events')
    op.drop_table('market_events')
    op.drop_index(op.f('ix_executions_trade_plan_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_execution_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_events_sequence'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_aggregate_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
