from typing import Dict, Any

from tradiba.hermes.live.approvals.workflow import ExecutionApprovalFramework
from tradiba.hermes.collective.consensus.engine import ConsensusEngine

class CollectiveGovernance:
    """
    Ensures collective consensus recommendations pass through the Execution Approval Framework.
    """
    def __init__(self, consensus_engine: ConsensusEngine, approval_framework: ExecutionApprovalFramework):
        self.consensus = consensus_engine
        self.approval_framework = approval_framework
        
    def process_collective_recommendation(self, recommendation: Dict[str, Any], current_state: Dict[str, Any]) -> str:
        """
        Takes a recommendation generated by consensus. Passes it to live governance.
        """
        # First verify consensus was valid
        if recommendation.get("consensus_status") != "APPROVED":
            return "REJECTED_BY_CONSENSUS"
            
        decision = recommendation.get("decision", {})
        risk_approved = recommendation.get("risk_approved", False)
        
        # Then enforce governance
        return self.approval_framework.process_decision(decision, current_state, risk_approved)
